name: owlet_lints
description: Lint rules for my flutter project with multi rules for the different project types.
version: 3.0.0
repository: https://github.com/sonnts996/owlet-lints

environment:
  sdk: ^3.1.0

dependencies: 
  flutter_lints: ^2.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
